# Generated by Django 5.1.4 on 2024-12-23 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainGame', '0003_alter_player_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='value',
            field=models.IntegerField(default=1),
        ),
    ]
