# Generated by Django 5.1.4 on 2024-12-24 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainGame', '0004_alter_card_value'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='card',
            name='game',
        ),
        migrations.RemoveField(
            model_name='card',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='card',
            name='value',
        ),
        migrations.RemoveField(
            model_name='game',
            name='is_active',
        ),
        migrations.AddField(
            model_name='card',
            name='is_house_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='lobby_code',
            field=models.CharField(default='DEFAULT_CODE', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='player',
            name='ninja_cards',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='HonorToken',
        ),
        migrations.RemoveField(
            model_name='player',
            name='honor_points',
        ),
        migrations.RemoveField(
            model_name='player',
            name='is_alive',
        ),
    ]
