# Generated by Django 5.1.4 on 2024-12-24 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainGame', '0006_game_is_active_game_players_alter_game_lobby_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
    ]
