# Generated by Django 5.1.4 on 2024-12-24 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainGame', '0007_delete_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='lobby_code',
            field=models.CharField(default='Default-Code', max_length=10, unique=True),
        ),
    ]
