# Generated by Django 5.1.4 on 2024-12-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainGame', '0009_lobby_player_delete_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='house_card',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='ninja_cards',
            field=models.JSONField(default=list),
        ),
    ]
