# Generated by Django 5.1.4 on 2025-01-01 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainGame', '0014_lobby_passed_cards_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='queued_cards',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
