# Generated by Django 5.1.4 on 2025-01-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainGame', '0016_remove_lobby_passed_cards_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='passed_cards',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='player',
            name='recieved_cards',
            field=models.JSONField(default=list),
        ),
    ]
