# Generated by Django 5.1.4 on 2025-01-07 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainGame', '0017_player_passed_cards_player_recieved_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
